server:
  port: 8083

spring:
  mail:
    username: 2033099424@qq.com
    password: ekhmhxswuqcmceaf
    host: smtp.qq.com
    properties:
      mail:
        smtp:
          ssl:
            enable: true
  rabbitmq:
    host: 124.223.27.13
    port: 5672
    username: guest
    password: guest
    virtualHost: / #rabbitmq未创建虚拟host默认配置
