server:
  port: 8080
spring:
  application:
    name: spring-serutity-demo
  main:
    allow-circular-references: true
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:~/test  #内存中建库
    username: sa  #设置h2库的用户名
    password: 123  #设置h2库的密码
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    show-sql: true